version:  '3.1'

services:
  app:
    command: bash -c "python ./easy_start.py"
    depends_on:
      - db
    links:
      - db:db
    image: aiohttp_example
    build
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./db/env
    ports:
      - "80:80"
    networks:
      - backend

  db:
    image: postgres
    restart: always
    env_file:
      - ./db/env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pg-data:

networks:
  backend:
    driver: bridge
